# Dependencies
markdown:         kramdown
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

exclude: ["deploy.sh", "LICENSE.md"]

# Setup
title:            Pwnies blog
description:      'A blog about hacking and CTFs'
domain: pwnies.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://pwnies.github.io  # the base hostname and protocol for your site, e.g. http://example.com
  #url:              http://pwnies.dk
baseurl:          /

paginate:         5
paginate_path: "/blog/page:num/"

